import boto3
from datetime import datetime, timezone, timedelta

ec2 = boto3.client('ec2')
ce = boto3.client('ce')
sns = boto3.client('sns')
s3 = boto3.client('s3')
dynamodb = boto3.resource('dynamodb')

table = dynamodb.Table('FinOpsProject')
TOPIC_ARN = 'arn:aws:sns:ap-southeast-1:563185858681:FinOpsAlert'
S3_BUCKET_NAME = 'projectbucketfinops'

def lambda_handler(event, context):

    report = []
    termination_recommendations = []
    s3_alerts = []
    s3_details = []

    # -------- EC2 GOVERNANCE LOGIC (STOP ONLY) --------
    instances = ec2.describe_instances(
        Filters=[{'Name': 'instance-state-name', 'Values': ['running']}]
    )

    for r in instances.get('Reservations', []):
        for i in r.get('Instances', []):

            instance_id = i['InstanceId']
            launch_time = i['LaunchTime']
            running_hours = (
                datetime.now(timezone.utc) - launch_time
            ).total_seconds() / 3600

            tags = {t['Key']: t['Value'] for t in i.get('Tags', [])}
            instance_name = tags.get('Name', 'Unnamed-EC2')

            if (
                running_hours > 0.1 and
                tags.get('AutoStop', '').strip().lower() == 'true' and
                tags.get('Critical', '').strip().lower() != 'yes'
            ):
                # ✅ STOP ONLY (NO TERMINATION)
                ec2.stop_instances(InstanceIds=[instance_id])
                action = "Stopped (Non-critical EC2 exceeded allowed runtime)"

                # 💡 RECOMMENDATION ONLY
                termination_recommendations.append(
                    f"- {instance_name} ({instance_id}) was STOPPED. "
                    f"If this instance is no longer required, it MAY be considered for TERMINATION after approval."
                )
            else:
                action = "Protected (Critical or within allowed runtime)"

            report.append(f"- {instance_name} ({instance_id}): {action}")

            table.put_item(Item={
                'ResourceId': instance_id,
                'InstanceName': instance_name,
                'Action': action,
                'Time': str(datetime.now())
            })

    # -------- S3 BUCKET ANALYSIS (READ-ONLY) --------
    try:
        response = s3.list_objects_v2(Bucket=S3_BUCKET_NAME)

        if 'Contents' not in response:
            s3_alerts.append(
                f"⚠ S3 bucket '{S3_BUCKET_NAME}' is empty. Consider deleting it if not required."
            )
        else:
            objects = response['Contents']
            s3_alerts.append(
                f"S3 bucket '{S3_BUCKET_NAME}' contains {len(objects)} object(s)."
            )

            for obj in objects:
                s3_details.append(
                    f"- Object: {obj['Key']}, Uploaded On: {obj['LastModified'].strftime('%Y-%m-%d %H:%M:%S')}"
                )

    except Exception as e:
        s3_alerts.append(
            f"⚠ Unable to analyze S3 bucket '{S3_BUCKET_NAME}'."
        )
        print("S3 ERROR:", e)

    # -------- COST EXPLORER ALERTS --------
    cost_alerts = []

    cost_data = ce.get_cost_and_usage(
        TimePeriod={
            'Start': (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d'),
            'End': datetime.now().strftime('%Y-%m-%d')
        },
        Granularity='MONTHLY',
        Metrics=['UnblendedCost'],
        GroupBy=[{'Type': 'DIMENSION', 'Key': 'SERVICE'}]
    )

    for g in cost_data['ResultsByTime'][0]['Groups']:
        if float(g['Metrics']['UnblendedCost']['Amount']) > 1:
            cost_alerts.append(
                f"⚠ {g['Keys'][0]} cost is higher than expected."
            )

    # -------- EMAIL ALERT (CLEAR WORDING) --------
    email_message = f"""
Good evening sir/madam,

This is an automated cloud governance and cost control alert generated by the AWS FinOps system.

EC2 Governance Actions (AUTO-STOP ONLY):
{chr(10).join(report) if report else "No EC2 actions were required today."}

EC2 Termination Recommendations (MANUAL REVIEW REQUIRED):
{chr(10).join(termination_recommendations) if termination_recommendations else "No EC2 termination recommendations at this time."}

S3 Bucket Summary:
{chr(10).join(s3_alerts) if s3_alerts else "No S3 optimization actions required."}

S3 Object Details:
{chr(10).join(s3_details) if s3_details else "No objects found in the bucket."}

Service Cost Alerts:
{chr(10).join(cost_alerts) if cost_alerts else "No abnormal service costs detected."}

NOTE:
This system does NOT terminate any EC2 instances automatically.

No production workloads were impacted.

Thank you.

Regards,
AWS FinOps & Cloud Governance System
(Automated Notification)
"""

    sns.publish(
        TopicArn=TOPIC_ARN,
        Subject="AWS FinOps Alert – Cloud Governance Notification",
        Message=email_message
    )

    return {"status": "FinOps execution completed"}
